# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("ProjSplx"); Pkg.test("ProjSplx"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("ProjSplx")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
